name: CI
on: [push]
jobs:
  build:
    name: Build, lint, and test on Node ${{ matrix.node }} and ${{ matrix.os }}

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: ['16.x', '18.x']
        os: [ubuntu-latest]

    services:
      ftp:
        image: delfer/alpine-ftp-server
        env:
          USERS: test|thisisapassword
        ports:
          - 21:21
          - 21000-21010:21000-21010

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Use Node ${{ matrix.node }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}

      - name: Install PNPM
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 6.0.2

      - name: Install deps and build (with cache)
        run: pnpm install  --no-frozen-lockfile

      - name: Lint
        run: pnpm lint

      - name: Test
        run: sleep 5 && pnpm test
        env:
          LOCAL_APIKEY: ${{ secrets.LOCAL_APIKEY }}

      - name: Build
        run: pnpm build

  coverage:
    name: coverage
    runs-on: ubuntu-latest
    services:
      ftp:
        image: delfer/alpine-ftp-server
        env:
          USERS: test|thisisapassword
        ports:
          - 21:21
          - 21000-21010:21000-21010
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "16"
      - uses: pnpm/action-setup@v4.1.0
        with:
          version: 6.0.2
      - run: pnpm install --no-frozen-lockfile
      - run: sleep 5 && pnpm test
        env:
          LOCAL_APIKEY: ${{ secrets.LOCAL_APIKEY }}
      - uses: paambaati/codeclimate-action@v9.0.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
        with:
          debug: true
